fix: rm `lume/` from `markdown-plugins` prefix
- `lume/markdown-plugins` worked locally but failed CI
  changed to `markdown-plugins` to avoid confusion with main lume module
  breaking builds

```
error: Uncaught (in promise) TypeError: Module not found
"https://cdn.jsdelivr.net/gh/lumeland/lume@3.1.3/markdown-plugins/footnotes.ts".
at https://deno.land/x/xeo@v7.0.1/plugins.ts:22:23
```